title: NBIS Theme for Studium
collections:
  examples:
    output: true
defaults:
  - scope:
      type: examples
      path: ""
    values:
      permalink: examples/:path:output_ext
      root: ..
liquid:
  error_mode: strict
exclude:
  - Gemfile
  - Gemfile.lock
theme: jekyll-theme-minimal